GET http://127.0.0.1:8000/api/v1/users/ HTTP/1.1
Authorization: Basic admin:admin
Content-Type: application/json
x-Refferal-Code: 123

###

GET http://127.0.0.1:8000/api/v1/users/ HTTP/1.1
Authorization: Basic demo:demo
Content-Type: application/json
x-Refferal-Code: 123


###

PATCH  http://127.0.0.1:8000/api/v1/users/me/ HTTP/1.1
Authorization: Basic demo:demo
Content-Type: application/json
x-Refferal-Code: 123


###

GET http://127.0.0.1:8000/api/v1/users/me/ HTTP/1.1
Authorization: Basic demo:demo
Content-Type: application/json
x-Refferal-Code: 123


###

POST http://127.0.0.1:8000/api/v1/users/upload-avatar/ HTTP/1.1
Host: 127.0.0.1:8000
Authorization: Basic demo:demo
Content-Length: 215
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="image_avatar.png"
Content-Type: image/jpeg

< ./image_avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

POST http://127.0.0.1:8000/api/v1/users/upload-cover/ HTTP/1.1
Host: 127.0.0.1:8000
Authorization: Basic demo:demo
Content-Length: 215
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="cover"; filename="image_cover.jpg"
Content-Type: image/jpeg

< ./image_cover.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

GET http://127.0.0.1:8000/api/v1/users/c3192401-b253-47e3-9a39-e7ad3e7312b0/ HTTP/1.1
Authorization: Basic demo:demo
Content-Type: application/json
x-Refferal-Code: 123

###

GET http://127.0.0.1:8000/api/v1/users/referral/ HTTP/1.1
Authorization: Basic admin:admin
Content-Type: application/json
x-Refferal-Code: 123

###

GET http://127.0.0.1:8000/api/v1/users/referral-codes/ HTTP/1.1
Authorization: Basic admin:admin
Content-Type: application/json
x-Refferal-Code: 123
