# Generated by Django 4.1.7 on 2023-03-14 16:47

from django.db import migrations, models

import auths.validators


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[auths.validators.AlphaNumericValidator()],
                verbose_name="username",
            ),
        ),
    ]
