# Generated by Django 4.1.7 on 2023-03-15 20:25

import auths.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters and digits only.",
                max_length=150,
                unique=True,
                validators=[auths.validators.AlphaNumericValidator()],
                verbose_name="username",
            ),
        ),
    ]
