# Generated by Django 4.2 on 2023-04-13 22:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0006_rename_user_taggeduser_content_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="auths.TaggedUser",
                to="auths.Tag",
                verbose_name="tags",
            ),
        ),
    ]
