# Generated by Django 4.2 on 2023-04-13 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0008_alter_user_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_id",
        ),
    ]
